export const mockAlertasData = {
  alertas: [
    {
      id: 1,
      tipo: 'critico',
      categoria: 'clima',
      titulo: 'Alerta de Geada',
      descricao: 'Previsão de temperatura abaixo de 2°C nos próximos 2 dias. Risco alto para lavouras de milho.',
      dataHora: new Date('2024-06-15T08:30:00'),
      lido: false,
      acoes: ['Cobrir mudas', 'Irrigação preventiva', 'Monitorar temperatura'],
      fazenda: 'Fazenda Santa Maria',
      talhoes: ['Talhão A', 'Talhão B'],
    },
    {
      id: 2,
      tipo: 'atencao',
      categoria: 'pragas',
      titulo: 'Detecção de Lagarta',
      descricao: 'Identificada presença de lagartas acima do nível de controle em talhão de soja.',
      dataHora: new Date('2024-06-15T14:20:00'),
      lido: false,
      acoes: ['Aplicar inseticida', 'Monitorar população', 'Vistoria diária'],
      fazenda: 'Fazenda Boa Vista',
      talhoes: ['Talhão C'],
    },
    {
      id: 3,
      tipo: 'informativo',
      categoria: 'mercado',
      titulo: 'Alta no Preço da Soja',
      descricao: 'Soja atingiu R$ 142,50/saca na B3. Momento favorável para comercialização.',
      dataHora: new Date('2024-06-15T10:15:00'),
      lido: true,
      acoes: ['Avaliar venda', 'Consultar corretora'],
      fazenda: null,
      talhoes: [],
    },
    {
      id: 4,
      tipo: 'critico',
      categoria: 'operacao',
      titulo: 'Estoque Baixo de Insumo',
      descricao: 'Fertilizante NPK 10-10-10 está com estoque abaixo do mínimo (12%).',
      dataHora: new Date('2024-06-14T16:45:00'),
      lido: false,
      acoes: ['Solicitar cotação', 'Programar compra', 'Ajustar planejamento'],
      fazenda: 'Fazenda Santa Maria',
      talhoes: [],
    },
    {
      id: 5,
      tipo: 'atencao',
      categoria: 'clima',
      titulo: 'Previsão de Seca',
      descricao: 'Modelo climático indica 15 dias sem chuva. Planeje irrigação suplementar.',
      dataHora: new Date('2024-06-14T09:00:00'),
      lido: true,
      acoes: ['Revisar sistema de irrigação', 'Calcular volume necessário'],
      fazenda: 'Fazenda Santa Maria',
      talhoes: ['Talhão A', 'Talhão D'],
    },
    {
      id: 6,
      tipo: 'informativo',
      categoria: 'operacao',
      titulo: 'Colheita Concluída',
      descricao: 'Colheita do Talhão E finalizada com produtividade de 64 sc/ha.',
      dataHora: new Date('2024-06-13T18:30:00'),
      lido: true,
      acoes: [],
      fazenda: 'Fazenda Boa Vista',
      talhoes: ['Talhão E'],
    },
    {
      id: 7,
      tipo: 'atencao',
      categoria: 'equipamento',
      titulo: 'Manutenção Programada',
      descricao: 'Trator John Deere 6155J necessita revisão dos 500 horas em 3 dias.',
      dataHora: new Date('2024-06-13T11:00:00'),
      lido: false,
      acoes: ['Agendar oficina', 'Separar peças', 'Planejar logística'],
      fazenda: 'Fazenda Santa Maria',
      talhoes: [],
    },
    {
      id: 8,
      tipo: 'informativo',
      categoria: 'regulatorio',
      titulo: 'Vencimento de Licença',
      descricao: 'Licença ambiental da Fazenda Santa Maria vence em 30 dias.',
      dataHora: new Date('2024-06-12T08:00:00'),
      lido: true,
      acoes: ['Protocolar renovação', 'Reunir documentos'],
      fazenda: 'Fazenda Santa Maria',
      talhoes: [],
    },
  ],
  estatisticas: {
    total: 8,
    naoLidos: 4,
    criticos: 2,
    atencao: 3,
    informativos: 3,
    porCategoria: [
      { categoria: 'Clima', total: 2, criticos: 1 },
      { categoria: 'Pragas', total: 1, criticos: 0 },
      { categoria: 'Mercado', total: 1, criticos: 0 },
      { categoria: 'Operação', total: 2, criticos: 1 },
      { categoria: 'Equipamento', total: 1, criticos: 0 },
      { categoria: 'Regulatório', total: 1, criticos: 0 },
    ],
  },
  configuracoes: {
    categorias: [
      { id: 'clima', nome: 'Clima', ativo: true, notificar: true },
      { id: 'pragas', nome: 'Pragas e Doenças', ativo: true, notificar: true },
      { id: 'mercado', nome: 'Mercado', ativo: true, notificar: false },
      { id: 'operacao', nome: 'Operação', ativo: true, notificar: true },
      { id: 'equipamento', nome: 'Equipamentos', ativo: true, notificar: false },
      { id: 'regulatorio', nome: 'Regulatório', ativo: true, notificar: false },
    ],
    niveis: [
      { id: 'critico', nome: 'Crítico', ativo: true, email: true, push: true },
      { id: 'atencao', nome: 'Atenção', ativo: true, email: true, push: false },
      { id: 'informativo', nome: 'Informativo', ativo: true, email: false, push: false },
    ],
  },
}
